<?xml version="1.0" encoding="utf-8"?><Database Name="BamiBread" Class="BamiBreadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-9ONRO0F\HEARTOFDEAD;Initial Catalog=BamiBread;Persist Security Info=True;User ID=nguyenxuanhoi2903" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BamiBreadConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameCategory" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Category_FastFood" Member="FastFoods" ThisKey="ID" OtherKey="IDCategory" Type="FastFood" />
    </Type>
  </Table>
  <Table Name="dbo.FastFood" Member="FastFoods">
    <Type Name="FastFood">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_FastFood" Member="Category" ThisKey="IDCategory" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Introduce" Member="Introduces">
    <Type Name="Introduce">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LinkImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TokenDevices" Member="TokenDevices">
    <Type Name="TokenDevice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StoreBami" Member="StoreBamis">
    <Type Name="StoreBami">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameStore" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneStore" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>